services:
  app:
    build: .
    container_name: painel_web
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: PainelView
      DJANGO_SUPERUSER_EMAIL: admin@exemplo.com
    command: >
      sh -c "
        /env/bin/python manage.py migrate &&
        /env/bin/python manage.py collectstatic --noinput &&
        /env/bin/python manage.py createsuperuser --noinput ||
        true &&
        /env/bin/gunicorn setup.wsgi:application --bind 0.0.0.0:80 --workers 3 --threads 2
      "
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "80"

  nginx:
    image: nginx:stable
    container_name: web_nginx
    ports:
      - "8080:80"
    volumes:
      - ./Painel_View/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - app

volumes:
  static_volume:
  media_volume:
