services:
  app:
    build: .
    container_name: web_app
    command: >
      sh -c "
        /env/bin/python manage.py migrate &&
        /env/bin/python manage.py collectstatic --noinput &&
        /env/bin/gunicorn setup.wsgi:application --bind 0.0.0.0:8080 --workers 3 --threads 2
      "
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8080"

  nginx:
    image: nginx:stable
    container_name: web_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - app

volumes:
  static_volume:
  media_volume:
