server {
    listen 80;
    server_name _;

    # Servindo os estáticos
    location /static/ {
        alias /app/staticfiles/;
        autoindex off;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Proxy para o Django/Gunicorn
    location / {
        proxy_pass http://app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
