server {
    listen 80;
    server_name _;

    # STATIC FILES
    location /static/ {
        alias /app/staticfiles/;
        try_files $uri $uri/ =404;
    }

    # MEDIA FILES
    location /media/ {
        alias /app/media/;
        try_files $uri $uri/ =404;
    }

    # DJANGO via Gunicorn
    location / {
        proxy_pass http://app:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
