# Generated by Django 5.2.8 on 2025-11-11 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Conexoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conexao', models.CharField(max_length=100, verbose_name='Nome da conexão')),
                ('url_origem', models.URLField(max_length=255, verbose_name='URL de origem')),
                ('client_id', models.CharField(max_length=200, verbose_name='Client ID')),
                ('client_secret', models.CharField(max_length=200, verbose_name='Client Secret')),
            ],
            options={
                'verbose_name': 'Conexão',
                'verbose_name_plural': 'Conexões',
                'db_table': 'tb_conexoes',
            },
        ),
        migrations.CreateModel(
            name='tb_Painel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do painel')),
                ('conexao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paineis', to='Administracao.tb_conexoes', verbose_name='Conexão')),
            ],
            options={
                'verbose_name': 'Painel',
                'verbose_name_plural': 'Painéis',
                'db_table': 'tb_painel',
            },
        ),
    ]
