# Generated by Django 5.2.8 on 2025-11-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_painel',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=8, verbose_name='Status'),
        ),
    ]
