# Generated by Django 5.2.8 on 2025-11-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0002_tb_painel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_painel',
            name='servicos_sga',
            field=models.JSONField(blank=True, help_text='Lista de IDs de serviços da unidade no SGA', null=True, verbose_name='Serviços da unidade (SGA)'),
        ),
        migrations.AddField(
            model_name='tb_painel',
            name='unidade_sga',
            field=models.IntegerField(blank=True, null=True, verbose_name='Unidade (SGA)'),
        ),
    ]
