# Generated by Django 5.2.8 on 2025-11-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0003_tb_painel_servicos_sga_tb_painel_unidade_sga'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_conexoes',
            name='pass_sga',
            field=models.CharField(default=1997, max_length=200, verbose_name='Senha SGA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tb_conexoes',
            name='user_sga',
            field=models.CharField(default=1997, max_length=200, verbose_name='User SGA'),
            preserve_default=False,
        ),
    ]
