# Generated by Django 5.2.8 on 2025-11-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0004_tb_conexoes_pass_sga_tb_conexoes_user_sga'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_conexoes',
            name='porta_mercure',
            field=models.IntegerField(default=3000, verbose_name='Porta Mercure'),
        ),
    ]
