# Generated by Django 5.2.8 on 2025-11-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0005_tb_conexoes_porta_mercure'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_conexoes',
            name='ip_mercure',
            field=models.CharField(default=10, max_length=9, verbose_name='IP do Mercure no servidor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tb_conexoes',
            name='client_id',
            field=models.CharField(max_length=200, verbose_name='Client ID SGA'),
        ),
        migrations.AlterField(
            model_name='tb_conexoes',
            name='client_secret',
            field=models.CharField(max_length=200, verbose_name='Client Secret SHA'),
        ),
        migrations.AlterField(
            model_name='tb_conexoes',
            name='porta_mercure',
            field=models.IntegerField(default=3000, max_length=5, verbose_name='Porta do Mercure'),
        ),
        migrations.AlterField(
            model_name='tb_conexoes',
            name='url_origem',
            field=models.URLField(max_length=255, verbose_name='URL do SGA'),
        ),
    ]
