# Generated by Django 5.2.8 on 2025-11-19 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0006_tb_conexoes_ip_mercure_alter_tb_conexoes_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_conexoes',
            name='ip_mercure',
            field=models.GenericIPAddressField(protocol='IPv4', verbose_name='IP do Mercure'),
        ),
    ]
