# Generated by Django 5.2.8 on 2025-11-24 14:01

import Administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0007_alter_tb_conexoes_ip_mercure'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioCampainha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Áudio')),
                ('arquivo', models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Áudio de Campainha',
                'verbose_name_plural': 'Áudios de Campainha',
            },
        ),
        migrations.AlterField(
            model_name='tb_conexoes',
            name='ip_mercure',
            field=models.GenericIPAddressField(help_text='Normalmente é o mesmo do servidor hospedado o SGA', protocol='IPv4', verbose_name='IP do Mercure'),
        ),
    ]
