# Generated by Django 5.2.8 on 2025-11-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0008_audiocampainha_alter_tb_conexoes_ip_mercure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiocampainha',
            name='nome',
        ),
    ]
