# Generated by Django 5.2.8 on 2025-11-24 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0009_remove_audiocampainha_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_painel',
            name='audio_campainha',
            field=models.ForeignKey(blank=True, help_text='Áudio tocado quando uma senha é chamada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Administracao.audiocampainha', verbose_name='Campainha do painel'),
        ),
    ]
