# Generated by Django 5.2.8 on 2025-11-27 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0010_tb_painel_audio_campainha'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Personalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convencional', models.CharField(default='#0250C4', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor da fonte Convencional')),
                ('prioridade', models.CharField(default='#FF0000', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor da fonte Prioridade')),
            ],
        ),
    ]
