# Generated by Django 5.2.8 on 2025-11-28 12:35

import Administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0011_tb_personalizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidiaPainel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Imagem', 'Imagem'), ('Vídeo', 'Vídeo')], max_length=10)),
                ('arquivo', models.FileField(upload_to='midias_painel/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo])),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
    ]
