# Generated by Django 5.2.8 on 2025-11-28 13:26

import Administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0012_midiapainel_alter_audiocampainha_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='midiapainel',
            name='data_upload',
        ),
        migrations.RemoveField(
            model_name='midiapainel',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
    ]
