# Generated by Django 5.2.8 on 2025-11-28 13:41

import Administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0013_remove_midiapainel_data_upload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigPainel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_exibicao_imagem', models.PositiveIntegerField(default=5, help_text='Tempo em segundos que cada imagem ficará na tela')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
    ]
