# Generated by Django 5.2.8 on 2025-12-03 18:20

import Administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0014_configpainel_alter_audiocampainha_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
        migrations.AlterField(
            model_name='tb_conexoes',
            name='porta_mercure',
            field=models.IntegerField(default=3000, verbose_name='Porta do Mercure'),
        ),
    ]
