# Generated by Django 5.2.8 on 2026-01-12 14:12

import Administracao.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0015_alter_audiocampainha_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midiapainel',
            options={'ordering': ['ordem', 'id'], 'verbose_name': 'Mídia do Painel', 'verbose_name_plural': 'Mídias do Painel'},
        ),
        migrations.AddField(
            model_name='audiocampainha',
            name='conexao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campainha', to='Administracao.tb_conexoes'),
        ),
        migrations.AddField(
            model_name='configpainel',
            name='tempo_popup',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
        migrations.AlterField(
            model_name='configpainel',
            name='tempo_exibicao_imagem',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.CreateModel(
            name='GrupoMidia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_id', models.IntegerField(verbose_name='ID do Setor (SGA)')),
                ('setor_nome', models.CharField(max_length=150, verbose_name='Nome do Setor (SGA)')),
                ('conexao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_midias', to='Administracao.tb_conexoes')),
            ],
            options={
                'verbose_name': 'Grupo de Mídia',
                'verbose_name_plural': 'Grupos de Mídia',
                'unique_together': {('conexao', 'setor_id')},
            },
        ),
        migrations.AddField(
            model_name='midiapainel',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midias', to='Administracao.grupomidia'),
        ),
        migrations.AddField(
            model_name='tb_painel',
            name='grupos',
            field=models.ManyToManyField(related_name='paineis', to='Administracao.grupomidia'),
        ),
    ]
