# Generated by Django 5.2.8 on 2026-01-26 13:18

import Administracao.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0016_alter_midiapainel_options_audiocampainha_conexao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Setores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=20, null=True, verbose_name='Nome do setor')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', verbose_name='Status')),
            ],
        ),
        migrations.RemoveField(
            model_name='tb_painel',
            name='grupos',
        ),
        migrations.RemoveField(
            model_name='midiapainel',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='audiocampainha',
            name='conexao',
        ),
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
        migrations.AddField(
            model_name='configpainel',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paineis_config', to='Administracao.tb_setores', verbose_name='Configuração Setor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='midiapainel',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paineis_midea', to='Administracao.tb_setores', verbose_name='Mideas do Setor'),
        ),
        migrations.AddField(
            model_name='tb_painel',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paineis_setor', to='Administracao.tb_setores', verbose_name='Setor Origem'),
        ),
        migrations.DeleteModel(
            name='GrupoMidia',
        ),
    ]
