# Generated by Django 5.2.8 on 2026-01-26 19:30

import Administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0017_tb_setores_remove_tb_painel_grupos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tb_setores',
            options={'verbose_name': 'Setor', 'verbose_name_plural': 'Setores'},
        ),
        migrations.AddField(
            model_name='midiapainel',
            name='exibir_popup',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Não')], default=1, verbose_name='Exibir no Pop-Up'),
        ),
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
    ]
