# Generated by Django 5.2.8 on 2026-01-26 20:00

import Administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0018_alter_tb_setores_options_midiapainel_exibir_popup_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configpainel',
            options={'verbose_name': 'Configuração do Painel', 'verbose_name_plural': 'Configruação dos Painéis'},
        ),
        migrations.AddField(
            model_name='midiapainel',
            name='texto',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
        migrations.AlterField(
            model_name='configpainel',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Tempo até exibição do Pop-Up'),
        ),
        migrations.AlterField(
            model_name='midiapainel',
            name='exibir_popup',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Não')], default=1, verbose_name='Exibir no Painel Lateral'),
        ),
        migrations.AlterField(
            model_name='midiapainel',
            name='tipo',
            field=models.CharField(choices=[('Imagem', 'Imagem'), ('Vídeo', 'Vídeo'), ('Texto', 'Texto')], max_length=10),
        ),
    ]
