# Generated by Django 5.2.8 on 2026-01-27 11:52

import Administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0019_alter_configpainel_options_midiapainel_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midiapainel',
            name='exibir_lateral',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Não')], default=1, verbose_name='Exibir no Painel Lateral'),
        ),
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
        migrations.AlterField(
            model_name='midiapainel',
            name='exibir_popup',
            field=models.IntegerField(choices=[(0, 'Sim'), (1, 'Não')], default=1, verbose_name='Exibir no Pop-Up'),
        ),
        migrations.AlterField(
            model_name='midiapainel',
            name='texto',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Texto para Exibição'),
        ),
    ]
