# Generated by Django 5.2.8 on 2026-01-27 12:29

import Administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0021_alter_audiocampainha_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
        migrations.AlterField(
            model_name='midiapainel',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='midias_painel/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo]),
        ),
    ]
