# Generated by Django 5.2.8 on 2026-01-27 12:40

import Administracao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0022_alter_audiocampainha_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configpainel',
            options={'verbose_name': 'Configuração do Painel', 'verbose_name_plural': 'Configuração dos Painéis'},
        ),
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
        migrations.AlterField(
            model_name='midiapainel',
            name='texto',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto para Exibição'),
        ),
    ]
