# Generated by Django 5.2.8 on 2026-01-28 11:55

import Administracao.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administracao', '0023_alter_configpainel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_personalizacao',
            name='cor_texto',
            field=models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(regex='^#[0-9A-Fa-f]{6}$')], verbose_name='Cor da fonte do texto'),
        ),
        migrations.AddField(
            model_name='tb_personalizacao',
            name='tamanho_texto',
            field=models.IntegerField(default=45, verbose_name='Tamanho da fonte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='audiocampainha',
            name='arquivo',
            field=models.FileField(upload_to='audios/', validators=[Administracao.models.validar_tamanho_arquivo, Administracao.models.validar_extensao_arquivo], verbose_name='Arquivo de áudio'),
        ),
    ]
